### ISSUE TITLE
Duplicate Channel Names in programming files - a problem?

### ISSUE THREAD

**Issue by mckoss** [QCaudron/repeater_roundabout#8]
Because we have multiple repeaters owned by some groups, we end up with duplicate channel names in our programming files (just the call sign of the controlling organization).

So it's difficult to identify the specific channel being used on the radio.  This may especially be a problem when "hunting" for contacts by scanning.  It won't be clear on which channel you are actually making contact.

Some radios have limited number of characters to disambiguate the channels if the full call sign is used as well.

Perhaps channel numbers should be preserved between all the programming files, so the channel number can be used to cross-reference a numbered list in the repeaters.md file (web page).

For example - these names might be good if they would fit:

WW7PSR-2m
WW7PSR-6m
WW7PSR-dmr

**Comment by QCaudron** [comment]
I imagine most of the digital radios may not have this issue because of their displays, but I am guessing the vast majority of HTs use liquid crystal with very limited space. My own radios stop at six and seven characters... which is truly unhelpful, we agree !

I'm not sure what to do about this. I am reluctant to have empty channels depending on the programming file, because it might be easy to oversee a bunch of repeaters that way. I was imagining that people might log channel numbers and then cross-reference with the file they used to program things. Maybe we should seek community input on this ?

**Comment by mckoss** [comment]
Baofeng has a 7-character limit for these.  So, most call signs would afford one additional digit.

If we add numbering to the HTML page, then retain the same numbering in the programming files, I think that would be helpful.

Alternatively, simple solution could be to rename displayed repeaters and WWPSR1, WWPSR2, etc. (without and mnemonic convention for band or mode - just a disambiguating digit - but only for the groups that have multiple repeaters).

**Comment by QCaudron** [comment]
So my only thought : I've asked people to log repeater callsign and output frequency, so that I can tell them apart. If we now introduce a new code that is sometimes a repeater callsign and sometimes isn't, it may get confusing. I don't think there's a clear answer here, but I'm inclined to generate files with no gaps and count on people logging internally their channel number.

As I type that, actually, perhaps the best is to ask folk to log a "RR Channel Number" and, as you say, generate files with gaps where needed so that numbering is consistent. Then we ask folk to log the repeater callsign and channel number, forgetting output frequency.

**Comment by mckoss** [comment]
Channel names can stay the same, only if we make channel numbers consistent.  My radio, does display channel number as well as channel name - so I would be able to tell which one I'm on.

I think logging a RR Channel Number is easier (as long as we don't change them during the contest!) for folks as well...so, I'd be in favor of that change as well.

**Comment by QCaudron** [comment]
Alright, I'll begin working on that.


Quentin CAUDRON, PhD
quentincaudron.com

**Comment by QCaudron** [comment]
Addressed by #17.

**Comment by mckoss** [comment]
I like it!
